### ISSUE TITLE
Best approach for adding a slider into menu?

### ISSUE THREAD

**Issue by large** [notDmDrl/pull_down_button#11]
Love the class, great work!
I have implemented it with great success. Makes a much better impression that the default popup-menu.

I recently had an request for adding a slider into the menu.
![image](https://user-images.githubusercontent.com/535446/211215934-adddeada-fec1-45eb-845c-8b84485c56a1.png)

What is the best approach to add an `PullDownMenuItem.slideable` item?

**Comment by notDmDrl** [comment]
Hi @large 

Apple (at least as of date) have not introduced a slider item for their menus, so there might not be any "official" implementation any time soon by me.

As of best approach to add any custom item, there is only one - your **slideable** item widget should extend [`PullDownMenuEntry`](https://github.com/notDmDrl/pull_down_button/blob/main/lib/src/items/entry.dart). That's pretty much it.

You can also ignore any overrides for `PullDownMenuEntry` (just use some placeholder values) since those would be removed in the next update.

Really quick example:

<details><summary>Code</summary>

```dart
class SliderExample extends PullDownMenuEntry {
  const SliderExample(
    this.initialValue,
    this.onChanged, {
    super.key,
  });

  final double initialValue;
  final ValueChanged<double> onChanged;

  @override
  Widget build(BuildContext context) => _Slider(
        initialValue: initialValue,
        onChanged: onChanged,
      );

  // Can be ignored
  @override
  double get height => 0;

  // Can be ignored
  @override
  bool get isDestructive => false;

  // Can be ignored
  @override
  bool get represents => false;
}

class _Slider extends StatefulWidget {
  const _Slider({
    required this.initialValue,
    required this.onChanged,
  });

  final double initialValue;
  final ValueChanged<double> onChanged;

  @override
  State<_Slider> createState() => _SliderState();
}

class _SliderState extends State<_Slider> {
  late double value = widget.initialValue;

  void onChanged(double v) {
    setState(() => value = v);

    widget.onChanged(v);
  }

  @override
  Widget build(BuildContext context) => Material(
        type: MaterialType.transparency,
        child: Slider(
          value: value,
          onChanged: onChanged,
        ),
      );
}
```
</details>

It is unfortunately slightly ugly aproach since `PullDownMenuEntry` extends `StatelessWidget`, but it should work

**Comment by large** [comment]
Hi @notDmDrl ,

Great feedback, I fully understand that a scrollbar will be little "outside" the scope of this.
With your tip for implementation I would add this slider https://pub.dev/packages/cupertino_range_slider_improved so it fall into the design.

Thank you for the help :)
