### ISSUE TITLE
Feature: Using the menu without navigator.push

### ISSUE THREAD

**Issue by iSa1vatore** [notDmDrl/pull_down_button#17]
Hi, I tried to use the menu for the chat preview, but the current implementation overlaps the page and blocks interaction.

Can we try to add using the menu without using navigator.push?

For the demonstration, I simply made MenuConfig and PullDownMenu public and inserted the menu as a widget.

| navigator.push  | without navigator.push |
| ------------- | ------------- |
| <video src="https://user-images.githubusercontent.com/42691184/224989498-7296f8ca-3a0d-4926-866a-b224cfbba081.mov"> | <video src="https://user-images.githubusercontent.com/42691184/224989460-8e5df6cd-da26-4c30-88cd-57a1157a268f.mov">  |

**Comment by notDmDrl** [comment]
Hi @iSa1vatore 

I guess we could expose `PullDownMenu` (with all animations removed i suppose) or add some public `PullDownMenuBody` or something (naming is hard :D) since adding MenuConfig to public scope might introduce some unnecessary verbosity.

Also, based on your vids, wouldn't it be better to use `CupertinoContextMenu`? Just curious

**Comment by iSa1vatore** [comment]
Yeah, I was thinking of creating something like "PullDownMenuBody" too, I made MenuConfig public only for demonstration purposes.

I don't really like the animations in CupertinoContextMenu, the menu looks a bit different (compared to your pull_down_button, which I use in the whole application) and as I understand it's not possible to put a scroll in the preview.

**Comment by notDmDrl** [comment]
Ok i'll try to release an update tomorrow

**Comment by iSa1vatore** [comment]
Thank you, good job!
