### ISSUE TITLE
Is it possible to implement this somehow?

### ISSUE THREAD

**Issue by rr8733380** [notDmDrl/pull_down_button#25]
Is it possible to somehow add the same thing as choosing an emoji to a telegram message?
Or not on top of the widget message, but at the top of the menu

<img src="https://user-images.githubusercontent.com/121060849/233802947-b745f9eb-7310-4a97-bf85-aba4f02642d0.jpg" width="60%" height="60%">

**Comment by notDmDrl** [comment]
Hi @rr8733380 

You can use the `PullDownMenu` widget (only the menu itself) and create all the required stuff (such as that emoji picker or blurred route) by yourself.

You can also try [`CupertinoContextMenu`](https://api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html) as it looks like a better choice for your request.

Similar to https://github.com/notDmDrl/pull_down_button/issues/17.

**Comment by rr8733380** [comment]
How can I implement this using `PullDownMenu`? Can you show me please?

**Comment by rr8733380** [comment]
Can I completely `PullDownMenuItem`? so that I can specify `child` for it instead of `title`?

**Comment by notDmDrl** [comment]
> How can I implement this using PullDownMenu? Can you show me please?

I looked closely at [HIG for menus](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/menus) and it seems like you want to create a context menu which is not in the scope of this package.

As I already mentioned, Flutter already has an iOS context menu with `CupertinoContextMenu‎`. I will advise you to use it.

I could try to come up with a working example using my package, but it will reuse a lot of code from `CupertinoContextMenu‎` implementation anyway so you're better off using `CupertinoContextMenu‎` in this case.

---

> Can I completely PullDownMenuItem? so that I can specify child for it instead of title?

Since this package tries to match native APIs for iOS menus closely, no you can't.

However, you're completely free to create your own menu items. The only thing required - is your custom item to implement `PullDownMenuEntry`:

```dart
class MyPullDownMenuItem extends StatelessWidget implements PullDownMenuEntry {
   const MyPullDownMenuItem(
     this.child,
     // everything else you need
   );
   
   final Widget child;

   // everything else you need
   @override
   Widget build(BuildContext context) {
     // your own implementation of a menu item
   }
}
```

**Comment by rr8733380** [comment]
thanks for the help boss
