### ISSUE TITLE
[iOS] App freezing

### ISSUE THREAD

**Issue by daniloapr** [notDmDrl/pull_down_button#29]
We have been experiencing some app freezing and even crashes while using the pull_down_button. It has been reported in production (--release mode) from our users and I just got it in debug: the app froze with one of the items highlighted as selected and only got back working after a hot reload. However, I really don't know if the library is the cause.

Has anyone experienced something like this before while using the `pull_down_button`?

`pull_down_button: ^0.8.3`

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-BR)
    • Flutter version 3.10.1 on channel stable at /Users/danilorego/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (3 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/danilorego/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • Danilo’s iPhone (mobile) • 00008101-001538162200801E            • ios            • iOS 16.5 20F66
    • iPhone 14 Pro (mobile)   • 9C0B392C-AEB7-4366-94A2-2A939007C734 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)          • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)             • chrome                               • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by notDmDrl** [comment]
Hi @daniloapr 

> the app froze with one of the items highlighted as selected and only got back working after a hot reload.

During development I noticed that this behavior usually happens when the menu is scrollable, however, it should not crash your app. 

I have tested an example app built with the **0.9.1** version of the package (on Android), and while multiple items can be "highlighted" because of this bug, no crashes are present.

Please test the **0.9.1** version first to see if the crash problem persists. If so, I'll try to come up with a fix as soon as possible. 

The multiple "highlighted" items bug might take some time to fix as I'm pretty busy enough 😄

**Comment by notDmDrl** [comment]
> Note that we don't have crash reports for Android, only for iOS

That's strange. I tried to get the crash on an Android too, but even with ~1500 items, there are only FPS drops which are expected since `SingleChildScrollView` is used internally for the scrollable menu.

Could you please look into stack traces of said crash reports? The culprit might show up there, thanks.
