### ISSUE TITLE
How can i open with initial value and scroll to before him

### ISSUE THREAD

**Issue by ziqq** [notDmDrl/pull_down_button#31]
Hello, how can i open with initial value and scroll to before him. And i need mark current value. Thx.

**Comment by notDmDrl** [comment]
Hi @ziqq 

Update 0.9.2 is live with `PullDownButton.initialScrollOffset` added. It exposes the [initialScrollOffset](https://api.flutter.dev/flutter/widgets/ScrollController/initialScrollOffset.html) property of the internal scrollable.

**Comment by ziqq** [comment]
I don't understand how can i get initialScrollOffset. Need implement `FixedExtentScrollController`.

**Comment by ziqq** [comment]
And more, can u add optional haptic feedback when menu is open, like iOS?

**Comment by ziqq** [comment]
@notDmDrl, How i can change `background` color for `PullDownMenuItem`?

**Comment by notDmDrl** [comment]
@ziqq

About `initialScrollOffset` - unfortunately, it is a bit clunky solution as I don't have time for anything more sophisticated. 

Bellow will be default sizes for various menu items (assuming the current `textScaleFactor` is 1, and every string is short enough to be one line only):

<details><summary>Menu item default sizes</summary>

- `PullDownMenuItem` - 44px;
- `PullDownMenuItem` with a subtitle - 64px;
- `PullDownMenuActionsRow.small` - 44px;
- `PullDownMenuActionsRow.medium` - 60px;
- `PullDownMenuHeader` - 64px;
- `PullDownMenuTitle` - 32px;
- `PullDownMenuDivider` - 0px;
- `PullDownMenuDivider.large` - 8px;

</details>

You can use those to eyeball the required scroll offset.

I am not sure what you meant about `FixedExtentScrollController`, since every item type in the menu has a different size, `FixedExtentScrollController` will not work here.

---

> And more, can u add optional haptic feedback when menu is open, like iOS?

There is already haptic feedback on swipe between different items. If you want haptic feedback when the menu opens, call the desired `HapticFeedback` variant before calling `onTap` from `PullDownButton.buttonBuilder`.

---

> How i can change background color for PullDownMenuItem?

You can change the background color for the entire menu using `PullDownMenuRouteTheme.backgroundColor`.

For `PullDownMenuItem` specifically, you can only change on hover and on press background color (you can change those values in `PullDownMenuItemTheme`). 

Based on guidelines, Apple does not allow customization of background color on a per-item basis (they do not allow changing even menu background color to my knowledge), so no in-package support for something like this.

However, you can copy this and wrap any menu item when needed:

```dart
@immutable
class MenuItemBackground extends StatelessWidget implements PullDownMenuEntry {
  const MenuItemBackground({
    super.key,
    required this.backgroundColor,
    required this.menuItem,
  });

  final Color backgroundColor;
  final PullDownMenuEntry menuItem;

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: backgroundColor,
      child: menuItem,
    );
  }
}
```

**Comment by ziqq** [comment]
> I am not sure what you meant about FixedExtentScrollController, since every item type in the menu has a different size, FixedExtentScrollController will not work here.

It would be nice to at least add ScrollController

**Comment by notDmDrl** [comment]
> It would be nice to at least add ScrollController

I guess passing `ScrollController` instead of `initialScrollOffset` will indeed be better. 

Update **0.9.3** is live. It removes `PullDownButton.initialScrollOffset` and adds `PullDownButton.scrollController` instead.

**Comment by notDmDrl** [comment]
@ziqq 

> we should use the FixedExtentScrollController how does it do CupertinoPicker

`CupertinoPicker` is completely different from pull-down menus, and just because `FixedExtentScrollController` is used there doesn't mean it can be used in pull-down menus. Also, as seen in your posted error, it is written that `FixedExtentScrollController` should be used in `ListWheelScrollView` which is once again a completely different thing that can't be used in pull-down menus.

I know it can be tempting to use `FixedExtentScrollController` because it already has a magic `initialItem` but as I already mentioned every pre-made menu item has a different size and also for the most part is not strictly constrained to a specific size either.

--- 

> And i try like this and it's not working to and it's not correctly

I am not sure what you meant by that, during testing it worked as expected. Please provide a complete example of your code, thanks.
