### ISSUE TITLE
[Feature Request] Expandable menu item that has sub-menu items. Visual reference in description.

### ISSUE THREAD

**Issue by NamanShergill** [notDmDrl/pull_down_button#36]
![IMG_6782](https://github.com/notDmDrl/pull_down_button/assets/33877135/b5a9d61a-0e80-4c74-b9cf-bd342b000081)
![IMG_6781](https://github.com/notDmDrl/pull_down_button/assets/33877135/bfac957b-ccf5-4de8-a67c-0fb95fba43ae)

**Comment by NamanShergill** [comment]
If any maintainer could chime in and share if this is something that wouldn’t be too complicated to implement for someone currently unfamiliar with the codebase, I could give it a shot.

**Comment by notDmDrl** [comment]
Hi @NamanShergill,

You can see the latest discussion around this topic here for some insight about the issue - https://github.com/notDmDrl/pull_down_button/issues/26

---

> if this is something that wouldn’t be too complicated to implement for someone currently unfamiliar with the codebase

I haven't actually tried to implement this yet. Still, I imagine it will be a rather challenging task as apparently, Flutter is not friendly towards animated nested menus (see https://github.com/notDmDrl/pull_down_button/issues/26#issuecomment-1668547484 for context).

Based on the latest updates from the Pull-Down button's issue in the Flutter repo, the PR is coming soon so you might want to wait for it before working on this if you want.

---

Since this is a duplicate of https://github.com/notDmDrl/pull_down_button/issues/26, I'll close this issue in favor of having all discussions and updates there.

**Comment by NamanShergill** [comment]
Ah, I see, thank you!
