### ISSUE TITLE
Keyboard disappears while PullDownButton menu is opened

### ISSUE THREAD

**Issue by seelrd** [notDmDrl/pull_down_button#42]
In my application, when I call `showMenu()` while keyboard is opened, keyboard disappears.
When I close PullDownButton's menu, keyboard shows up again.

Where should I look in the code to change this behavior?

**Comment by notDmDrl** [comment]
Hi @seelrd 

I am not sure what the issue is. `Navigator` automatically closes the keyboard on a new route pushed (`showMenu()` uses `Navigator` under the hood).

Based on a [quick StackOverflow search](https://stackoverflow.com/a/66342525) `Navigator` does not currently have support for maintaining the keyboard state on route push/pop.

You might want to try the following example in the same StackOverflow question - https://stackoverflow.com/a/70643556

--- 

> Where should I look in the code to change this behavior?

As I mentioned above - `PullDownButton` uses `Navigator` (as well as `PopupRoute` internally), so unless you want to completely rewrite it by not using routes and `Navigator`, I don't see a possible way to "change this behavior". 

However, if you want to, here is the place the menu is opened from ([code](https://github.com/notDmDrl/pull_down_button/blob/main/lib/src/pull_down_button.dart#L455))

**Comment by seelrd** [comment]
Thank you for your quick and detailed response!
