### ISSUE TITLE
Can we set minimum menu height? 

### ISSUE THREAD

**Issue by hbt1903** [notDmDrl/pull_down_button#44]
It would be great to set the minimum menu height 🙏🏼  
Cuz when it can open the menu on top of the widget, it opens at to the top, even if there is only 1 visible item from the menu. And the rest of the menu should be scrolled but it does not give a nice user experience to scroll in such a small area. So, if we could specify the minimum height for the menu, the problem would be solved.

Here is an example
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-08 at 21 01 39](https://github.com/notDmDrl/pull_down_button/assets/26011820/d4ade768-ee59-462a-a79c-ade6185e4067)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-08 at 21 01 44](https://github.com/notDmDrl/pull_down_button/assets/26011820/8f5d2bd1-ec35-4e07-bf20-073345570aa0)

**Comment by notDmDrl** [comment]
Hi @hbt1903 

The problem is, that the menu already tries to fit as much space as possible. Could you try setting `PullDownButton.position` to `PullDownMenuPosition.over`? Alternatively, you can try to use `showPullDownMenu` and see if it is better in your particular use case.

If none of that helps, please provide a reproducible example so I can closely look into it.

Thanks
