### ISSUE TITLE
How to dismiss PullDownMenuItem manually

### ISSUE THREAD

**Issue by fyxtc** [notDmDrl/pull_down_button#45]
I use  ```GestureDetector``` as  ```iconWidget``` in ```PullDownMenuItem```. I want ```GestureDetector/onTap``` can close ui

**Comment by notDmDrl** [comment]
Hi @fyxtc 

I am unsure why you want to "manually dismiss" a menu item while it is already doing it on tap. 

However, for that specific use case, something like this should be good enough:

```dart
// If you want to close the menu without action triggered afterward.
GestureDetector(
  onTap: () => PullDownMenuItem.defaultTapHandler(context, null),
),

// or
GestureDetector(
  onTap: () => Navigator.pop(context),
),

// If you want to close the menu with additional action - pass the [PullDownMenuItem.onTap] callback that you usually provide to normal menu items here.
GestureDetector(
  onTap: () => PullDownMenuItem.defaultTapHandler(context, () { /* do something after menu closes */}),
),
```

Additionally, I would advise you to wrap `GestureDetector` with `Builder` so that your custom `iconWidget` has the correct information about `Navigator`.

**Comment by fyxtc** [comment]
@notDmDrl Very helpful, thank you for your prompt reply, this library is very helpful to me, my app uses it heavily, thank you for developing such a great library!
