### ISSUE TITLE
Force rebuild of PullDownMenuItem to implement a multi select drop down

### ISSUE THREAD

**Issue by falt008** [notDmDrl/pull_down_button#51]
Hi I am currently trying to use this package to implement an iOS style multi select dropdown. I have a PullDownMenuItem.selectable for each item and use selected to represent selection. I use a tapHandler to prevent the menu to close after an item is tapped and in the onTap I toggle the selection boolean via setState. My problem is that this does not cause a rebuild of the items. I tried giving the Items and the PulldownButton itself a key which would change if the selection changes however this did not work. Do you have an idea how I could force the rebuild of the PullDownMenuItems?

```dart
// minimal example
PullDownMenuItem.selectable(
    title: 'Example',
    onTap: () => setState(() => toggle = !toggle),
    key: Key(toggle.toString()),
    tapHandler: _itemTapHandler,
    selected: toggle,
),
```

**Comment by falt008** [comment]
One approach which is working is creating a custom Stateful PullDownMenuItem which rebuilds itself on interaction. However I don't know if this is the best approach. What do you think?

```dart
class SelectionItem extends StatefulWidget implements PullDownMenuEntry {
  const SelectionItem({super.key});

  @override
  State<SelectionItem> createState() => _SelectionItemState();
}

class _SelectionItemState extends State<SelectionItem> {
  bool toggle = false;

  @override
  Widget build(BuildContext context) {
    return PullDownMenuItem.selectable(
      title: 'Ceta',
      onTap: () => setState(() {
        toggle = !toggle;
      }),
      key: Key(toggle.toString()),
      tapHandler: _itemTapHandler,
      selected: toggle,
    );
  }

  void _itemTapHandler(BuildContext context, VoidCallback? onTap) {
    if (true) {
      onTap?.call();
    } else {
      Navigator.pop(context, onTap);
    }
  }
}
```

**Comment by notDmDrl** [comment]
Hi @falt008,

Yes, menu items are not supposed to be rebuildable, and even something like `tapHandler` should not exist there if we look strictly at how menus are behaving on iOS.

> Do you have an idea how I could force the rebuild of the PullDownMenuItems?

Well, sort of - here is an old example that does exactly what you need - https://github.com/notDmDrl/pull_down_button/issues/27#issuecomment-1545380358. It uses `ValueNotifier` under the hood.

> One approach which is working is creating a custom Stateful PullDownMenuItem which rebuilds itself on interaction. However I don't know if this is the best approach. What do you think?

If that works for you then I don't see anything wrong with it. My `ValueNotifier` example is, well, an example - you are free to use whatever state management you want 😄.

---

Also to add to your code example, I would advise you to use `PullDownMenuItem.noPopTapHandler` instead of `_itemTapHandler` - no need to create your own "no pop" handler :)

**Comment by falt008** [comment]
Hi @notDmDrl,

alright thats good to know. I think I will stick to my approach with the custom widget. Thank you for the tip with `PullDownMenuItem.noPopTapHandler`!
